=== karzhouAndrew/Java-Homework/Ivashkevich/src/classwork/plants/Plants.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Plants" type="PlantsType"/>
  <xs:complexType name="PlantsType">
    <xs:sequence>
      <xs:element type="categoryType" name="category" maxOccurs="unbounded" minOccurs="0"/>
        <xs:element type="valueType" name="totalPlantHeight" maxOccurs="unbounded" minOccurs="0"/>
        <xs:element type="valueType" name="Bush" maxOccurs="unbounded" minOccurs="0"/>
        <xs:element type="valueType" name="Tree" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="plantType">
    <xs:sequence>
      <xs:element type="xs:string" name="name"/>
      <xs:element type="xs:string" name="height"/>
      <xs:element type="xs:string" name="age"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="categoryType">
    <xs:sequence>
      <xs:element type="xs:string" name="Title"/>
      <xs:element type="plantType" name="plant" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
    <xs:simpleType name="valueType">
        <xs:restriction base="xs:double"/>
    </xs:simpleType>
</xs:schema>

=== karzhouAndrew/Java-Homework/Ivashkevich/src/classwork/plants/Plants_modify.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><Plants xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Plants.xsd">
    <category>
        <Title>Tree</Title>
       <plant>
           <name>buk</name>
           <height>4.5</height>
           <age>3.0</age>
       </plant>
        <plant>
            <name>oak</name>
            <height>9.0</height>
            <age>6.0</age>
        </plant>
    </category>
    <category>
        <Title>Bush</Title>
        <plant>
            <name>lilac</name>
            <height>0.4</height>
            <age>2.5</age>
        </plant>
        <plant>
            <name>currant</name>
            <height>7.3</height>
            <age>4.2</age>
        </plant>
        <plant>
            <name>gooseberry</name>
            <height>3.1</height>
            <age>0.2</age>
        </plant>
    </category>
<totalPlantHeight>24.3</totalPlantHeight><Bush>3</Bush><Tree>2</Tree></Plants>

=== karzhouAndrew/Java-Homework/Ivashkevich/src/classwork/plants/Plants.xml
<?xml version="1.0"?>
<Plants xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="Plants.xsd">
    <category>
        <Title>Tree</Title>
       <plant>
           <name>buk</name>
           <height>1.5</height>
           <age>1</age>
       </plant>
        <plant>
            <name>oak</name>
            <height>2</height>
            <age>5</age>
        </plant>
    </category>
    <category>
        <Title>Bush</Title>
        <plant>
            <name>lilac</name>
            <height>0.4</height>
            <age>0.5</age>
        </plant>
        <plant>
            <name>currant</name>
            <height>0.3</height>
            <age>0.2</age>
        </plant>
        <plant>
            <name>gooseberry</name>
            <height>0.1</height>
            <age>0.2</age>
        </plant>
    </category>
</Plants>
