=== karzhouAndrew/Java-Homework/sokolov/src/workbook2/lab5/Unit.dtd
<?xml version = "1.0" encoding="UTF-8"?>
<!ELEMENT pointList (point*)>
        <!ELEMENT point (x,y)>
<!ATTLIST point unit ("cm") #REQUIRED>
        <!ELEMENT x (#PCDATA)>
        <!ELEMENT y (#PCDATA)>
        <!ELEMENT point2 (x2,y2)>
        <!ATTLIST point2 unit ("mm") #REQUIRED>
        <!ELEMENT x2 (#PCDATA)>
        <!ELEMENT y2 (#PCDATA)>
        <!ELEMENT point3 (x3,y3)>
        <!ATTLIST point3 unit ("px") #REQUIRED>
        <!ELEMENT x3 (#PCDATA)>
        <!ELEMENT y3 (#PCDATA)>

        <!--Для xml, сделанного в предыдущем задании, создайте DTD с жестко заданными значениями параметра units тега point -->

=== karzhouAndrew/Java-Homework/sokolov/src/workbook2/lab4/Unit.XML
<?xml version = "1.0" ?>
<!DOCTYPE pointList SYSTEM "Unit.dtd">
<pointList>
    <point unit="cm">
        <x>2</x>
        <y>3</y>
    </point>
    <point unit="mm">
        <x>90</x>
        <y>38</y>
    </point>
    <point unit="px">
        <x>57</x>
        <y>64</y>
    </point>
</pointList>

<!--Сделайте XML на основе приведенного примера, у которого тег point будет иметь параметр unit - единицы измерения.
 Возможные значения - cm,mm,px.  -->
