=== karzhouAndrew/Java-Homework/markovich/src/classes/lab11/garden.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.w3schools.com"
           xmlns="http://www.w3schools.com"
           elementFormDefault="qualified">
    <xs:element name="garden">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="tree" type="treeType" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="shrub" type="shrubType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="treeType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="age" type="xs:decimal"/>
            <xs:element name="height" type="xs:decimal"/>
            <xs:element name="trunk" type="xs:decimal"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="shrubType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="age" type="xs:decimal"/>
            <xs:element name="height" type="xs:decimal"/>
            <xs:element name="berries" type="xs:boolean"/>
            <xs:element name="flowers" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== karzhouAndrew/Java-Homework/markovich/src/classes/lab11/newGarden.xml
<?xml version="1.0" encoding="UTF-8"?>
<garden xmlns="http://www.w3schools.com"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.w3schools.com garden.xsd">
	<tree>
		<name>Arborvitae</name>
		<age>3.3</age>
		<height>2.59</height>
		<trunk>10.84</trunk>
	</tree>
	<tree>
		<name>Butternut</name>
		<age>3.8</age>
		<height>2.99</height>
		<trunk>6.84</trunk>
	</tree>
	<tree>
		<name>Hawthorns</name>
		<age>2.6</age>
		<height>2.29</height>
		<trunk>3.84</trunk>
	</tree>
	<tree>
		<name>Baobab</name>
		<age>4.1</age>
		<height>3.6900000000000004</height>
		<trunk>20.84</trunk>
	</tree>
	<shrub>
		<name>Abelia</name>
		<age>3.6</age>
		<height>1.62</height>
		<berries>true</berries>
		<flowers>blue</flowers>
	</shrub>
	<shrub>
		<name>Buddleja</name>
		<age>3.2</age>
		<height>1.42</height>
		<berries>true</berries>
		<flowers>pink</flowers>
	</shrub>
	<shrub>
		<name>Clianthus</name>
		<age>3.9000000000000004</age>
		<height>1.52</height>
		<berries>false</berries>
		<flowers>white</flowers>
	</shrub>
	<shrub>
		<name>Zanthoxylum</name>
		<age>2.8</age>
		<height>1.7200000000000002</height>
		<berries>false</berries>
		<flowers>yellow</flowers>
	</shrub>
	<shrub>
		<name>Zenobia pulverulenta</name>
		<age>2.9000000000000004</age>
		<height>1.32</height>
		<berries>true</berries>
		<flowers>aquamarine</flowers>
	</shrub>
</garden>

=== karzhouAndrew/Java-Homework/mikhailiuk/src/workbook2/garden/entity/garden.xml
<?xml version= "1.0" encoding="UTF-8"?>
<garden xmlns="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.w3schools.com garden.xsd">
    <tree leaftype="deciduous" fruittype="none">
        <name>oak</name>
        <age>113</age>
        <height>18.3</height>
    </tree>
    <tree leaftype="deciduous" fruittype="none">
        <name>birch</name>
        <age>25</age>
        <height>22.5</height>
    </tree>
    <tree leaftype="deciduous" fruittype="apples">
        <name>apple</name>
        <age>5</age>
        <height>4.5</height>
    </tree>
    <tree leaftype="coniferous" fruittype="none">
        <name>cedar</name>
        <age>69</age>
        <height>32.8</height>
    </tree>
    <bush hedgetype="no" blossomtype="yes">
        <name>lilac</name>
        <age>4</age>
        <height>2.5</height>
    </bush>
    <bush hedgetype="yes" blossomtype="no">
        <name>laurels</name>
        <age>3</age>
        <height>1.7</height>
    </bush>
</garden>
